//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyZoo.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListAnimal
    {
        public int Id { get; set; }
        public Nullable<int> AnimalId { get; set; }
        public Nullable<int> ZooId { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual ZooCompany ZooCompany { get; set; }
    }
}
