//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyZoo.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZooCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZooCompany()
        {
            this.ListAnimal = new HashSet<ListAnimal>();
        }
    
        public int Id { get; set; }
        public string Address { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
        public string Direcror { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListAnimal> ListAnimal { get; set; }
    }
}
